// GENERATED FILE - do not edit by hand.
// Metal Shading Language vertex shader generated by slangc from
// rhi/testdata/sanity_color.slang (entry point vertexMain).
// Regenerate from the repo root with:
//   build/tools/slang/bin/slangc rhi/testdata/sanity_color.slang -target metal -entry vertexMain -stage vertex -o c3/test/rhi/testdata/sanity_color.vert.metal
// then re-add this header.

#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 18 "rhi/testdata/sanity_color.slang"
struct vertexMain_Result_0
{
    float4 position_0 [[position]];
    float4 color_0 [[user(COLOR)]];
};


#line 10
struct Push_0
{
    float4 color_1;
};




struct VSOutput_0
{
    float4 position_1;
    [[flat]] float4 color_2;
};


#line 18
[[vertex]] vertexMain_Result_0 vertexMain(uint vid_0 [[vertex_id]], Push_0 constant* push_0 [[buffer(0)]])
{

#line 26
    thread VSOutput_0 o_0;

    (&o_0)->position_1 = float4(float2(float((vid_0 << 1U) & 2U), float(vid_0 & 2U)) * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);
    (&o_0)->color_2 = push_0->color_1;

#line 29
    thread vertexMain_Result_0 _S1;

#line 29
    (&_S1)->position_0 = o_0.position_1;

#line 29
    (&_S1)->color_0 = o_0.color_2;

#line 29
    return _S1;
}

