// GENERATED FILE - do not edit by hand.
// Metal Shading Language fragment shader generated by slangc from
// rhi/testdata/sanity_color.slang (entry point fragmentMain).
// Regenerate from the repo root with:
//   build/tools/slang/bin/slangc rhi/testdata/sanity_color.slang -target metal -entry fragmentMain -stage fragment -o c3/test/rhi/testdata/sanity_color.frag.metal
// then re-add this header.

#include <metal_stdlib>
#include <metal_math>
#include <metal_texture>
using namespace metal;

#line 18 "rhi/testdata/sanity_color.slang"
struct pixelOutput_0
{
    float4 output_0 [[color(0)]];
};


#line 18
struct pixelInput_0
{
    [[flat]] float4 color_0 [[user(COLOR)]];
};


#line 34
[[fragment]] pixelOutput_0 fragmentMain(pixelInput_0 _S1 [[stage_in]], float4 position_0 [[position]])
{

#line 34
    pixelOutput_0 _S2 = { _S1.color_0 };
    return _S2;
}

